# Generated by Django 6.0.6 on 2026-06-09 17:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Paciente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, verbose_name='Nombre')),
                ('apellido_paterno', models.CharField(max_length=100, verbose_name='Apellido paterno')),
                ('apellido_materno', models.CharField(blank=True, max_length=100, verbose_name='Apellido materno')),
                ('fecha_nacimiento', models.DateField(verbose_name='Fecha de nacimiento')),
                ('sexo', models.CharField(choices=[('M', 'Masculino'), ('F', 'Femenino'), ('O', 'Otro')], max_length=1, verbose_name='Sexo')),
                ('estado_civil', models.CharField(choices=[('S', 'Soltero/a'), ('C', 'Casado/a'), ('D', 'Divorciado/a'), ('V', 'Viudo/a'), ('U', 'Unión libre')], max_length=1, verbose_name='Estado civil')),
                ('tipo_sangre', models.CharField(blank=True, choices=[('A+', 'A+'), ('A-', 'A-'), ('B+', 'B+'), ('B-', 'B-'), ('AB+', 'AB+'), ('AB-', 'AB-'), ('O+', 'O+'), ('O-', 'O-')], max_length=3, verbose_name='Tipo de sangre')),
                ('curp', models.CharField(blank=True, max_length=18, unique=True, verbose_name='CURP')),
                ('rfc', models.CharField(blank=True, max_length=13, verbose_name='RFC')),
                ('telefono', models.CharField(max_length=20, verbose_name='Teléfono')),
                ('telefono_emergencia', models.CharField(blank=True, max_length=20, verbose_name='Teléfono de emergencia')),
                ('contacto_emergencia', models.CharField(blank=True, max_length=200, verbose_name='Contacto de emergencia')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='Correo electrónico')),
                ('calle', models.CharField(max_length=200, verbose_name='Calle y número')),
                ('colonia', models.CharField(blank=True, max_length=100, verbose_name='Colonia')),
                ('ciudad', models.CharField(max_length=100, verbose_name='Ciudad')),
                ('estado', models.CharField(max_length=100, verbose_name='Estado')),
                ('codigo_postal', models.CharField(blank=True, max_length=10, verbose_name='Código postal')),
                ('alergias', models.TextField(blank=True, verbose_name='Alergias conocidas')),
                ('enfermedades_cronicas', models.TextField(blank=True, verbose_name='Enfermedades crónicas')),
                ('medicamentos_actuales', models.TextField(blank=True, verbose_name='Medicamentos actuales')),
                ('notas', models.TextField(blank=True, verbose_name='Notas adicionales')),
                ('fecha_registro', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
                ('activo', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Paciente',
                'verbose_name_plural': 'Pacientes',
                'ordering': ['apellido_paterno', 'apellido_materno', 'nombre'],
            },
        ),
        migrations.CreateModel(
            name='Hospitalizacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hospital', models.CharField(max_length=200)),
                ('numero_expediente', models.CharField(blank=True, max_length=100)),
                ('cama', models.CharField(blank=True, max_length=20)),
                ('motivo', models.CharField(choices=[('CIR', 'Cirugía programada'), ('URG', 'Urgencia'), ('OBS', 'Observación'), ('MAT', 'Maternidad'), ('DIA', 'Estudio diagnóstico'), ('OTR', 'Otro')], max_length=3)),
                ('diagnostico_ingreso', models.TextField()),
                ('diagnostico_egreso', models.TextField(blank=True)),
                ('medico_responsable', models.CharField(max_length=200)),
                ('fecha_ingreso', models.DateTimeField()),
                ('fecha_egreso', models.DateTimeField(blank=True, null=True)),
                ('estado', models.CharField(choices=[('ING', 'Ingresado'), ('INT', 'En tratamiento'), ('ALT', 'Alta médica'), ('TRA', 'Transferido'), ('FAL', 'Fallecido')], default='ING', max_length=3)),
                ('procedimientos', models.TextField(blank=True)),
                ('observaciones', models.TextField(blank=True)),
                ('fecha_registro', models.DateTimeField(auto_now_add=True)),
                ('paciente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hospitalizaciones', to='pacientes_app.paciente')),
            ],
            options={
                'verbose_name': 'Hospitalización',
                'verbose_name_plural': 'Hospitalizaciones',
                'ordering': ['-fecha_ingreso'],
            },
        ),
        migrations.CreateModel(
            name='SeguroMedico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('aseguradora', models.CharField(max_length=200, verbose_name='Aseguradora')),
                ('numero_poliza', models.CharField(max_length=100, verbose_name='Número de póliza')),
                ('numero_grupo', models.CharField(blank=True, max_length=100)),
                ('nombre_titular', models.CharField(max_length=200, verbose_name='Nombre del titular')),
                ('parentesco_titular', models.CharField(blank=True, max_length=100)),
                ('vigencia_inicio', models.DateField()),
                ('vigencia_fin', models.DateField(blank=True, null=True)),
                ('telefono_aseguradora', models.CharField(blank=True, max_length=20)),
                ('cobertura_descripcion', models.TextField(blank=True)),
                ('activo', models.BooleanField(default=True)),
                ('fecha_registro', models.DateTimeField(auto_now_add=True)),
                ('paciente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='seguros', to='pacientes_app.paciente')),
            ],
            options={
                'verbose_name': 'Seguro médico',
                'verbose_name_plural': 'Seguros médicos',
            },
        ),
    ]
