# Generated by Django 6.0.6 on 2026-06-09 18:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pacientes_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Receta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField()),
                ('peso', models.CharField(blank=True, max_length=20, verbose_name='Peso (kg)')),
                ('talla', models.CharField(blank=True, max_length=20, verbose_name='Talla (cm)')),
                ('diagnostico', models.TextField(verbose_name='Diagnóstico')),
                ('indicaciones', models.TextField(verbose_name='Indicaciones médicas')),
                ('medico', models.CharField(blank=True, max_length=200, verbose_name='Médico')),
                ('fecha_registro', models.DateTimeField(auto_now_add=True)),
                ('paciente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recetas', to='pacientes_app.paciente')),
            ],
            options={
                'verbose_name': 'Receta',
                'verbose_name_plural': 'Recetas',
                'ordering': ['-fecha_registro'],
            },
        ),
    ]
