# Generated by Django 6.0.6 on 2026-06-25 21:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pacientes_app', '0002_receta'),
    ]

    operations = [
        migrations.CreateModel(
            name='Consulta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateTimeField()),
                ('doctor', models.CharField(blank=True, max_length=200)),
                ('peso', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True, verbose_name='Peso (kg)')),
                ('notas', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('paciente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='consultas', to='pacientes_app.paciente')),
            ],
            options={
                'verbose_name': 'Consulta',
                'verbose_name_plural': 'Consultas',
                'ordering': ['-fecha'],
            },
        ),
        migrations.CreateModel(
            name='HistoriaClinica',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_realizada', models.DateTimeField(blank=True, null=True)),
                ('doctor_que_realizo', models.CharField(blank=True, max_length=200)),
                ('motivo_consulta', models.TextField(blank=True)),
                ('peso_actual', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('peso_maximo_historico', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('peso_mas_bajo_adulto', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('peso_adolescencia', models.CharField(blank=True, max_length=200)),
                ('edad_inicio_aumento_peso', models.CharField(blank=True, max_length=200)),
                ('eventos_asociados_aumento_peso', models.JSONField(blank=True, default=list)),
                ('intentos_previos_perder_peso', models.CharField(blank=True, max_length=200)),
                ('especifique_intentos', models.CharField(blank=True, max_length=500)),
                ('medicamentos_usados', models.CharField(blank=True, max_length=500)),
                ('resultados_obtenidos', models.TextField(blank=True)),
                ('peso', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True, verbose_name='Peso medido (kg)')),
                ('talla', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Talla (cm)')),
                ('imc', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='IMC')),
                ('porcentaje_grasa_corporal', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('porcentaje_grasa_visceral', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('masa_muscular', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('cirugias_previas', models.TextField(blank=True)),
                ('hospitalizaciones_previas', models.TextField(blank=True)),
                ('tabaquismo', models.CharField(blank=True, choices=[('nunca', 'Nunca'), ('ocasional', 'Ocasional'), ('frecuente', 'Frecuente'), ('exfumador', 'Exfumador')], max_length=20)),
                ('alcohol', models.CharField(blank=True, choices=[('nunca', 'Nunca'), ('social', 'Social'), ('frecuente', 'Frecuente')], max_length=20)),
                ('actividad_fisica', models.CharField(blank=True, choices=[('sedentario', 'Sedentario'), ('ligera', 'Ligera'), ('moderada', 'Moderada'), ('intensa', 'Intensa')], max_length=20)),
                ('horas_sueno', models.CharField(blank=True, max_length=100)),
                ('calidad_sueno', models.CharField(blank=True, choices=[('buena', 'Buena'), ('interrumpida', 'Interrumpida'), ('mala', 'Mala')], max_length=20)),
                ('numero_comidas_dia', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('desayuno_habitual', models.CharField(blank=True, max_length=500)),
                ('comida_habitual', models.CharField(blank=True, max_length=500)),
                ('cena_habitual', models.CharField(blank=True, max_length=500)),
                ('snacks', models.CharField(blank=True, max_length=500)),
                ('consumo_bebidas_azucaradas', models.CharField(blank=True, choices=[('nunca', 'Nunca'), ('ocasional', 'Ocasional'), ('frecuente', 'Frecuente')], max_length=20)),
                ('consumo_comida_rapida', models.CharField(blank=True, max_length=200)),
                ('come_grandes_volumenes', models.BooleanField(default=False)),
                ('come_rapido', models.BooleanField(default=False)),
                ('come_por_ansiedad', models.BooleanField(default=False)),
                ('come_sin_hambre', models.BooleanField(default=False)),
                ('episodios_atracon', models.BooleanField(default=False)),
                ('come_durante_noche', models.BooleanField(default=False)),
                ('preferencia_alimento', models.CharField(blank=True, max_length=200)),
                ('especifique_preferencia', models.CharField(blank=True, max_length=500)),
                ('estado_emocional_actual', models.CharField(blank=True, choices=[('estable', 'Estable'), ('ansioso', 'Ansioso'), ('deprimido', 'Deprimido'), ('otro', 'Otro')], max_length=20)),
                ('tratamiento_psicologico_previo', models.BooleanField(default=False)),
                ('trastornos_conducta_alimentaria_previos', models.TextField(blank=True)),
                ('glucosa_ayuno', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('perfil_lipidico', models.TextField(blank=True)),
                ('cirugia_bariatrica', models.BooleanField(default=False)),
                ('procedimiento_propuesto', models.CharField(blank=True, max_length=200)),
                ('especifique_procedimiento', models.CharField(blank=True, max_length=500)),
                ('observaciones', models.TextField(blank=True)),
                ('conclusiones', models.TextField(blank=True)),
                ('fecha_registro', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
                ('paciente', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='historia_clinica', to='pacientes_app.paciente')),
            ],
            options={
                'verbose_name': 'Historia clínica',
                'verbose_name_plural': 'Historias clínicas',
            },
        ),
    ]
